name: Build Anduril server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Go source code
        uses: actions/checkout@v3
      - name: Prepare Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: go get .
      - name: Build Go source code
        run: go build -v -o out/anduril-server
